name: yubikit_openpgp
description: Yubikey OpenPGP interface. Smartcard interface can be replaced for different platforms like Flutter.
version: 1.0.9
homepage: https://github.com/Producement/yubikit-openpgp

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  convert: ^3.0.1
  tuple: ^2.0.0
  crypto: ^3.0.1
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0