name: yubikit_openpgp
description: Yubikey OpenPGP interface. Smartcard interface can be replaced for different platforms like Flutter.
version: 1.0.13
homepage: https://github.com/Producement/yubikit-openpgp

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  convert: ^3.0.1
  tuple: ^2.0.0
  collection: ^1.16.0
  jwk: ^0.1.1
  cryptography: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  pointycastle: ^3.6.0
  test: ^1.16.0